### ISSUE TITLE
Port Roveberrypy processes to robocluster

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/robocluster#12]
As a sanity test of how easy robocluster is to use, someone should port some of the rover processes from Roveberrypy to the new robocluster Pub/Sub framework. Most interesting is something that reads data from hardware devices, and something that maintains some sort of state, like navigation code.

- [X] GPSProcess
- [x] DriveProcess
- [ ] ~WebServer~ Webserver is getting redone
- [X] Navigation Process

**Comment by jpas** [comment]
As a note for this, I should probably not be implementing these as I wrote the device code.

**Comment by ottopasuuna** [comment]
I'm just going to close this issue as this is basically done. Some testing is still needed, but the GPS and Joystick processes work for sure, and drive shouldn't take much work to get going. Robocluster may still change a bit especially with regard to serial devices, so it's hard to come to a conclusion about how it is to work with, but it isn't worse to deal with than Roveberrypy, so it should be good.
