### ISSUE TITLE
Windows 10. "The requested address is not valid in its context"

### ISSUE THREAD

**Issue by tyrelkostyk** [UofSSpaceTeam/robocluster#16]
Tried running device.py from the robocluster/examples repo. Installed setup.py and have anaconda3, to no avail. Not too sure what the problem is but it's most certainly because of some compatibility issue between Windows 10 & Linux(the OS for which this example was originally coded).
```
C:\Users\Tyrel\robocluster\examples>python device.py
Traceback (most recent call last):
  File "device.py", line 10, in <module>
    device_a = Device('device-a', group)
  File "C:\Users\Tyrel\Anaconda3\lib\site-packages\robocluster-0.1-py3.6.egg\robocluster\device.py", line 58, in __init__
    self._receiver.bind()
  File "C:\Users\Tyrel\Anaconda3\lib\site-packages\robocluster-0.1-py3.6.egg\robocluster\net.py", line 64, in bind
    self._socket.bind(self._address)
OSError: [WinError 10049] The requested address is not valid in its context
```

**Comment by ottopasuuna** [comment]
@tyrelkostyk can you try the device.py example again and confirm that it's fixed? I probably should have waited to merge that branch but oh well.

**Comment by jpas** [comment]
I'm going to assume that closing this issue means that my fix has resolved it.
