### ISSUE TITLE
Device refactoring and definition

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/robocluster#28]
One of the major goals of developing the new framework was to make supporting multiple transport mediums seamless, so we can send messages over ethernet/wireless, USB/UART serial, SPI, I2C, CAN bus, etc using the same API. The current implementation of SerialDevice seems a bit tacked on with regards to its integration with Device, and feels inconsistant with how you interact IP multicast communication. The goal of this issue is to:
- Define exactly what a Device is.
- Propose a restructuring of the Device internals to better accomodate new transport mediums, protocols, and callbacks.
- Do this all in a way that is applicable to other implementations such as C/C++, Arduino.

The following is my suggestion, which may or may not also represent the current implementation.
### Device
A "Device" is an entity that allows you to connect to the robocluster "network", and performs basic task management and callbacks triggered by messages incomming on a "Port". The Device would contain a collection of "Ports", a "Router", a callback look-up table, a collection of "Tasks", and local storage for synchronizing data amongst "Tasks". This aligns with the current implementation of a "Device", with the addition of a "Router" and local storage (which is already being developed). My thinking is that a "Device" can be thought of as a "virtual microcontroller", or an RTOS running on a microcontroller, in that it as ports for i/o and tasks can be registerd like interupt subroutines or scheduled to be run periodically. A "Device" would provide an easy interface to manage tasks, and send and recieve data on the network, while all the grunt work would be handled by other classes instanciated within the device.
The advantage of having an analogy like this is it makes it easy to understand conceptually of how robocluster works, making it easier to document and organize development, and should make it easy to port over to a real microcontroller.

### Ports and Routers
A "Port" is like a socket in network programming, but also applies to interfaces such as serial, I2C, etc. We also don't have to call them "Ports" if that's confusing with the ports in TCP/UDP. When you want to publish a message to the network, data is writen to the UDP or Multicast port. If you send a message directly to another Device, it is send over the TCP port. If you send a message to a microcontroller connected with serial, it is sent over the serial port. You could also explicitly state which ports you want a message to be sent over, or all of them if you wish. A "Router" is just the thing that handles the distribution of messages to the right place. Though now that I think of it, the Router may not be necessary as its own entity at all. When message is read from a "Port", the event goes through the callback look up table to trigger the correct task. A task can be registered to trigger on an event from any "Port", or a specific set of "Ports", and multiple tasks can be triggered from a single event.
In the case of TCP and serial ports, a Device has one port for each serial device or other Device it wants to talk to, and are referenced by the name of the downstream device. So sending a message to deviceB could look like: `deviceA.send(msg, port='deviceA')`

### Tasks
These are just your standard coroutines/functions. An additional feature that would be useful, is the ability to add or remove tasks easily while the Device is running. Tasks can keep track of persistant state within the Device via a storage mechanism, probably just a AttributeDictionary where you can put what ever you need inside.

[Here is an image for an overview of a Device](https://drive.google.com/file/d/1C0JdDWcqLHI5A1UvVkNNM6krt32skQ8y/view?usp=sharing)

### Message format
Messages look something like this:
```
msg = {
  'event': 'event_name',
  'data'  : <whatever data>,
  'ports' : [ list of ports or port to send over],
  'sender' : 'device that sent the data'
}
```
We can just add more things to the message as we need.
When you call `publish` or `send`, the Device will automatically add the sender information and could assist in the ports part.
When a port sends the message, it could remove the ports field, as the receiving end doesn't care. In which case the ports field may be completely unneccessary if the Router is not its own entity inside the Device.

### Device methods
List of some of the methods Device will implement:
- `publish(event, data, ports=ALL)` Broadcast an event
- `send(device, data)` Sends data directly to a device, connecting via TCP if not done already
- `on(event, callback, ports=ALL)` Register a callback for an event
- `read(port=Serial) -> data` Reads data from a port. Reallly only usefull for Serial device that can't use JSON for what ever reason.
- `request(device, event) -> data` Requests data from another Device, identified with event.
- `reply(device, data)` Sends the data to the device that requested it.

Probably a bunch more asyncio wrappers like `sleep` and what not, but these should be the main communication ones.

I might be forgetting something, but this is probably enough for discussion.

This is mostly a refactoring of what we already have, just need to solidify the "Ports" concept and figure out what we want to do for the "Router".

**Comment by jpas** [comment]
# Device
The name makes a lot more sense now that we have defined it's purpose and how it works.

We need to keep device local storage around.

We need some kind of way of storing which devices live where and what ports they have exposed. This could be kept track of using some kind of distributed consensus algorithm or some kind of heartbeat based advertise network.

# Device methods
* `publish`, I agree that ports should be a kwarg, but we should support collections for this argument.
* `read`, I don't think this should be on the device itself, maybe syntax like this:
```py
device.ports['some-serial'].read()
```
* `on`, lets try and keep decorator support for this.

# Router
This is can probably be a specialized task within the device.

# Ports
Ports are a good name for this. I don't think it's confusing for tcp/udp ports either. I ran across [multiaddr](https://github.com/multiformats/multiaddr) the other day and it may be a good way to specify ports.

# Tasks
We need to figure out a good way to cancel tasks. I have idea on how to go about it, but it's way down in the weeds of asyncio.

# Message format
I think a message should have a list of ports associated with it.

**Comment by tyrelkostyk** [comment]
Definitely a helpful write up! I find myself being a little confused over the use of the "Port" term however, perhaps due to my limited experience with ports & network sockets. Initially you said that each Device would have a collection of "Ports", and I wasn't sure what was meant by this, as later on in an example you had deviceA send a message to deviceB, and in that expression you defined `port='deviceA'` .  I guess I'm confused on what exactly these "virtual ports" are, and how they'll be utilized. I think I understand how "ports" are an attribute of each message & that determines where the message will go, but just not how the ports are defined/connected to the Devices themselves, if that makes sense.

Other than that though everything makes sense to me! I agree that if the "router" can be something defined for each Device, that would likely be a lot easier to implement/understand than a standalone entity.

**Comment by ottopasuuna** [comment]
In the case of something like TCP, you would need to specify an IP address to send it to.
What I meant with `port='deviceA'` was that deviceA what be the "address" you send to. Same with Serial Ports, a device could have multiple serial devices, so you would have to specify which device to send to. I can see why that parameter name is confusing though, maybe `dest` would be better.

**Comment by ottopasuuna** [comment]
Or the multiaddr thing that Jarrod linked to may be good as well instead of a function parameter.

**Comment by ottopasuuna** [comment]
I've been working on the whole "Ports" thing, as well as adding a TCP port and getting the whole `send` mechanism going. A few points for discussion:

I want the devices to find each other automatically so the user/developer doesn't have to hardcode the ip addresses or port numbers when using `send` or `request/rely`. I'm currently thinking of achieving this as follows:
1. `deviceA.send("deviceB", somedata)`
1. deviceA starts a listening/server socket on an available port.
1. deviceA `publish`es a `SEND_REQUEST` to the network, with `"deviceB"` and address:port for deviceA's new server socket as the data.
1. deviceB (and all other devices) is subscribed to `SEND_REQUEST` and if the requested device is `"deviceB"`, it creates a new listening/server socket on an available port, and creates another client socket to connect to deviceA's server socket.
1. deviceB sends a `SEND_CONFIRM` (or something) directly to deviceA's server socket containing deviceB's address:port.
1. deviceA recieves the `SEND_CONFIRM` and creats a client socket connecting to the now known deviceB address:port.
1. deviceA sends the data.

Connections remain persistant after sending to make all future `send`s imediate. Are there any better ideas to achieve this functionality? This is susseptible to a malicious device claiming to be another device, but I can't think of a way to avoid this besides some crypto-signature and having a set of known/trusted devices. Security isn't an issue for our particular use case, but it would be good to keep it in mind.

I'm also looking ahead to the request/reply mechanism, and am wondering if we should add a "type" field to messages. From a high level, I want all messages to be routed through devices in the same manner, but messages that are published, direct send, request/reply, expect to behave slightly differently. For example, to run a callback when you receive a certain event/mesasge, you use the same`@device.on('event-name')` for everything, but a request message expects a reply so if you treat a request over TCP the same as a "direct send" over TCP, issues could arise. Another situation would be if a device such as a microcontroller only has one hardware interface (UART serial for example), all messages look the same, which may be what you want from an abstract point of view but makes it difficult to do proper error handling.

**Comment by ottopasuuna** [comment]
This refactoring is done. There may be other minor changes in the near future, but things are more or less sorted out.
