### ISSUE TITLE
UnkownPeer exception thrown before Devices have a chance to talk to eachother

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/robocluster#48]
This is more of a convenience request.
If we have two processes:
Replier:
``` python
from robocluster import Device
dev = Device('replier', 'test')
@dev.on_request('topic')
def give_thing():
  return 'Hi'
dev.start()
dev.wait()
```

Requester:
``` python
from robocluster improt Device
dev = Device('requester', 'test')
@dev.every('1s')
async def get_thing():
   data = await dev.request('replier', 'topic')
   print(data)
dev.start()
dev.wait()
```

Running this as is results in an UnknownPeer getting raised.
Catching the exception allows things to run properly.

It would be slick if it could somehow wait for a round of heartbeats (or however this works now) before throwing the exception, to give devices on the network a chance to anounce themselves.

**Comment by jpas** [comment]
Fixed by #51
